# Generated by Django 5.0.1 on 2024-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
