# Generated by Django 5.0.1 on 2024-01-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_product_digital_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
