# Generated by Django 5.0.1 on 2024-01-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_shippingaddress_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='Food',
        ),
    ]
