# Generated by Django 5.0.1 on 2024-01-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_rename_product_food_rename_product_orderitem_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Food',
            new_name='food',
        ),
    ]
